@startuml
actor Клиент as Client
actor Барыга as Sidor

package "Артефактик" {
    usecase "Выставить заказ" as CreateOrder
    usecase "Заполнить информацию" as FillOrderInfo
    usecase "Опубликовать" as PublishOrder

    usecase "Создать заказ по шаблону" as CreateOrderByTemplate
    usecase "Выбрать шаблон артефакта" as SelectOrderTemplate

    CreateOrder ..> FillOrderInfo : "Включает"
    CreateOrder ..> PublishOrder : "Включает"
    
    CreateOrderByTemplate ..> SelectOrderTemplate : "Includes"
    CreateOrderByTemplate .> FillOrderInfo : "Includes"
    CreateOrderByTemplate ..> PublishOrder : "Includes" 

    usecase "Принять заказ" as AcceptOrder
    usecase "Отправить уведомление" as SendNotification
    usecase "Получить уведомление о новом заказе" as ReceiveNotification

    usecase "Открыть список доступных заказов" as GetOrderList

    PublishOrder ..> SendNotification : "Includes"
    ReceiveNotification <... SendNotification : "Includes"

    GetOrderList .> ReceiveNotification: "Includes"
    AcceptOrder .> GetOrderList : "Includes"
}

Client --> CreateOrder
Client --> CreateOrderByTemplate
Sidor --> AcceptOrder
Sidor --> ReceiveNotification
Sidor --> GetOrderList 
@enduml