@startuml
actor "Торговец оружием" as GunSeller
actor Сталкер as Stalker

package Артефактик {


    usecase "Посмотреть список доступного оружия" as GetGunList
    
    usecase "Выбрать нужное оружие" as SelectGun

    usecase "Сделать заказ на оружие" as CreateGunOrder

    usecase "Получить уведомление о новом заказе" as OrderNotification

    usecase "Принять заказ на оружие" as AcceptGunOrder

    usecase "Отклонить заказ на оружие" as DeclineGunOrder

    usecase "Посмотреть информацию о новом заказе" as GetOrderInfo

    usecase "Открыть список предлагаемых заказов" as GetOrderList


    CreateGunOrder .> SelectGun: Includes
    SelectGun .> GetGunList: Includes

    GetOrderInfo .-up-> GetOrderList: Includes
    GetOrderList .> OrderNotification : Includes

    AcceptGunOrder .-down-> GetOrderInfo: Includes
    DeclineGunOrder .-down-> GetOrderInfo: Includes
    
 
}


GunSeller --> OrderNotification
GunSeller --> AcceptGunOrder 
GunSeller --> DeclineGunOrder 
GunSeller --> GetOrderList
Stalker --> CreateGunOrder
Stalker --> GetGunList

@enduml