@startuml
actor Барыга as Client

package Артефактик {
    usecase "Принять заказ" as AcceptOrder
    usecase "Открыть список доступных заказов" as ListOrders
    
    usecase "Предложить заказ сталкеру" as SuggestToStalker
    usecase "Отправить курьеру" as Courier

    AcceptOrder .-down-> ListOrders: "Includes"

    AcceptOrder .-down-> SuggestToStalker: "Includes"
    Courier .> AcceptOrder: "Includes"
}

Client --> AcceptOrder
Client --> ListOrders

Client --> Courier
@enduml