@startuml
actor Барыга as Sidor
actor Курьер as Courier

package Артефактик {
    usecase "Предложить заказ курьеру" as SuggestOrder
    usecase "Открыть список курьеров" as OpenCourierList
    usecase "Выбрать курьера" as SelectCourier
    usecase "Выбрать заказ" as SelectOrder
    usecase "Открыть список готовых заказов" as OpenOrderList

    usecase "Принять заказ" as AcceptOrder
    usecase "Отказаться от заказа" as RejectOrder

    SuggestOrder .-left-> SelectCourier: "Includes" 
    SuggestOrder.> SelectOrder: "Includes"

    SelectOrder.> OpenOrderList: "Includes"
    SelectCourier .-left-> OpenCourierList: "Includes"
}

Sidor --> SuggestOrder
Sidor --> OpenOrderList
Sidor --> OpenCourierList

Courier--> AcceptOrder
Courier--> RejectOrder
@enduml