@startuml
actor Барыга as Sidor
actor "Торговец оружием" as GunSeller
actor Курьер as Courier

actor "Владелец товара" as Owner

Owner <|-- Sidor
Owner <|-- GunSeller

package Артефактик {
    usecase "Предложить заказ курьеру" as SuggestOrder
    usecase "Открыть список курьеров" as OpenCourierList
    usecase "Выбрать курьера" as SelectCourier
    usecase "Выбрать заказ" as SelectOrder
    usecase "Открыть список готовых заказов" as OpenOrderList

    usecase "Принять заказ" as AcceptOrder
    usecase "Отказаться от заказа" as RejectOrder

    SuggestOrder .--> SelectCourier: "Includes" 
    SuggestOrder.> SelectOrder: "Includes"

    SelectOrder.> OpenOrderList: "Includes"
    SelectCourier .--> OpenCourierList: "Includes"
}

Owner--> SuggestOrder
Owner--> OpenOrderList
Owner--> OpenCourierList

Courier--> AcceptOrder
Courier--> RejectOrder
@enduml