@startuml
|Клиент: Мобильное приложение|
start


:Аутентификоваться в приложении;

|Сервер|
:Проверить наличие пользователя;
if (пользователь существует) then (да)
    :Вернуть токен авторизации;
else (нет)
    :Вернуть сообщение об ошибке;
    end
endif

|Клиент: Мобильное приложение|
:Запросить список атрефактов;
|Сервер|
:Вернуть список артефактов;
|Клиент: Мобильное приложение|
:Выбрать артефакт;
:Создать заказ;
|Сервер|
:Сохранить заказ в базе;
:Отправить уведомление о создании нового заказа;


|Барыга: Мобильное приложение|
:Получить уведомление о новом заказе;
:Запросить список доступных заказов;
|Сервер|
:Вернуть доступные заказы для Барыги;
|Барыга: Мобильное приложение|
:Выбрать новый заказ;
if (заказ устраивает) then (да)
    :Принять заказ;
else (нет)
    :Отклонить заказ;
endif

|Сервер|
:Сохранить изменение статуса заказа;
:Отправить уведомление об изменении статуса;

|Клиент: Мобильное приложение|
:Получить уведомление об изменении статуса заказа;

stop
@enduml


