@startuml
|Клиент: Мобильное приложение|
start


:Аутентификоваться в приложении
**POST** /api/auth/login;

|Сервер|
:Проверить наличие пользователя;
if (пользователь существует) then (да)
    :Сгенерировать JWT;
    :Вернуть JWT пользователю;
else (нет)
    :Вернуть сообщение об ошибке;
    end
endif

|Клиент: Мобильное приложение|
:Запросить список атрефактов
**GET** /api/artifacts
**Headers**: Authorization: Bearer <token>
;

|Сервер|
:Вернуть список артефактов: JSON;
|Клиент: Мобильное приложение|
:Выбрать артефакт;
:Создать заказ
**POST** /api/order
**Headers**: Authorization: Bearer <token>
**Body**: JSON
;

|Сервер|
:Сохранить заказ в базе;
:Отправить уведомление о создании нового заказа: JSON;


|Барыга: Мобильное приложение|
:Получить уведомление о новом заказе
**GET** /api/notifications
**Headers**: Authorization: Bearer <token>;
:Запросить список доступных заказов
**GET** /api/orders/available
**Headers**: Authorization: Bearer <token>;
|Сервер|
:Вернуть доступные заказы для Барыги: JSON;
|Барыга: Мобильное приложение|
:Выбрать новый заказ;
if (заказ устраивает) then (да)
    :Принять заказ
**PUT** /api/order
**Headers**: Authorization: Bearer <token>;
  
else (нет)
    :Отклонить заказ
**PUT** /api/order
**Headers**: Authorization: Bearer <token>;
  
endif

|Сервер|
:Сохранить изменение статуса заказа;
:Отправить уведомление об изменении статуса: JSON;

|Клиент: Мобильное приложение|
:Получить уведомление об изменении статуса заказа
**GET** /api/notifications
**Headers**: Authorization: Bearer <token>;

stop
@enduml


