@startuml


package Controllers {
    class ArtifactController
    Repository.ArtifactRepository <--* ArtifactController

    class AuthController
    Repository.UserRepository <--* AuthController
    Security.JwtGenerator <.. AuthController

    class InformationController 
    Repository.InformationRepository <--* InformationController
    Repository.UserRepository <--* InformationController


    class NotificationController
    Repository.NotificationRepository <--* NotificationController
    
    class OrdersController
    Repository.OrderRepository <--* OrdersController
    Repository.UserRepository <--* OrdersController
    Repository.NotificationRepository <--* OrdersController
    Util.Consts <.. OrdersController    

    class RoleController
    Util.Consts <.. RoleController

    class UserController
    Repository.UserRepository <--* UserController
    Util.FilenameGenerator <.. UserController
    Util.Consts <.. UserController
   
}

package Repository {
    interface ArtifactRepository
    Models.Artifact <.. ArtifactRepository

    interface InformationRepository
    Models.Information <.. InformationRepository

    interface NotificationRepository
    Models.Notification <.. NotificationRepository

    interface OrderRepository
    Models.Order <.. OrderRepository

    interface UserRepository
    Models.User <.. UserRepository
}



package Security {

    class UserDetailService
    Repository.UserRepository <--* UserDetailService

    class JwtGenerator

}


package Models {
    class Artifact
    
    class Information
    
    class Notification
    
    class Order

    
    class OrderStatus
    
    class User

    Order o--> User
    Order o--> OrderStatus
    Order o--> Artifact
   
    Information o--> User
    
    Notification o--> User
    Notification o--> Order

    

}

package Requests {

}

package Responses {

}

package Util {
    class FilenameGenerator

    class Consts

}

Requests <.. Controllers
Responses <.. Controllers



@enduml


