
@startuml


participant Барыга[
    Барыга
    ----
    ""Мобильное приложение""
]

participant Сталкер[
    Сталкер
    ----
    ""Мобильное приложение""
]


activate Барыга
Барыга -> Сервер: Запрос принятых заказов
activate Сервер
return Список принятых заказов

Барыга -> Барыга: Выбор заказа

Барыга -> Сервер: Запрос доступных сталкеров
activate Сервер
return Список доступных сталкеров

Барыга -> Сервер: Предложить заказ сталкеру
deactivate Барыга
activate Сервер
Сервер -> Сталкер: Уведомление о новом заказе
deactivate Сервер
activate Сталкер
Сталкер -> Сервер: Запрос информации о заказе
activate Сервер
return Подробная информация о заказе

alt Заказ устраивает сталкера
    Сталкер -> Сервер: Принять заказ
    activate Сервер
    Сервер -> Барыга: уведомление об изменении статуса заказа
    deactivate Сервер
else Заказ не устраивает
    Сталкер -> Сервер: Отклонить заказ
    activate Сервер
    Сервер -> Барыга: уведомление об изменении статуса заказа
    deactivate Сервер
end

@enduml
