
@startuml


participant Барыга[
    Барыга
    ----
    ""Мобильное приложение""
]

participant Сталкер[
    Сталкер
    ----
    ""Мобильное приложение""
]


activate Барыга
Барыга -> Сервер: Запрос принятых заказов: GET /api/orders
activate Сервер
return Список принятых заказов: JSON

Барыга -> Барыга: Выбор заказа

Барыга -> Сервер: Запрос доступных сталкеров: GET /api/users/stalkers
activate Сервер
return Список доступных сталкеров: JSON

Барыга -> Сервер: Предложить заказ сталкеру: POST /api/order/suggest
deactivate Барыга
activate Сервер
Сервер -> Сталкер: Уведомление о новом заказе: GET /api/notifications
deactivate Сервер
activate Сталкер
Сталкер -> Сервер: Запрос информации о заказе: GET /api/order
activate Сервер
return Подробная информация о заказе: JSON

alt Заказ устраивает сталкера
    Сталкер -> Сервер: Принять заказ: POST /api/order/accept
    activate Сервер
    Сервер -> Барыга: уведомление об изменении статуса заказа: GET /api/notifications
    deactivate Сервер
else Заказ не устраивает
    Сталкер -> Сервер: Отклонить заказ: POST /api/order/decline
    activate Сервер
    Сервер -> Барыга: уведомление об изменении статуса заказа: GET /api/notifications
    deactivate Сервер
end

@enduml
