@startuml


state "Новый заказ" as NewOrder
state "Принят барыгой" as AcceptedByHuckster
state "Предложен сталкеру" as SuggestedToStalker
state "Принят сталкером" as AcceptedByStalker
state "В процессе" as InProgress
state "Передан барыге" as TransferredToHuckster
state "Отправлен клиенту" as Sent
state "Завершен" as Completed
state "Отклонен барыгой" as Canceled
[*] -right-> NewOrder
NewOrder-right-> AcceptedByHuckster
NewOrder: ИдСостояния: State.New

AcceptedByHuckster: ИдентификаторБарыги: ID
AcceptedByHuckster --> SuggestedToStalker
AcceptedByHuckster: ИдСостояния: State.AcceptedByHuckster
AcceptedByHuckster --> Canceled


SuggestedToStalker: ИдентификаторПредложенногоСталкера: ID
SuggestedToStalker --> AcceptedByStalker
SuggestedToStalker --> AcceptedByHuckster

AcceptedByStalker: ИдентификаторСталкера: ID
AcceptedByStalker: ИдСостояния: State.AcceptedByStalker
AcceptedByStalker --> InProgress

Canceled: ИдСостояния: State.Canceled
Canceled -> NewOrder

InProgress: ИдСостояния: State.InProgress
InProgress -right-> TransferredToHuckster

TransferredToHuckster: ИдСостояния: State.TransferredToHuckster
TransferredToHuckster -right-> Sent

InProgress --> AcceptedByHuckster

Sent: ИдКурьера: ID
Sent: ИдСостояния: State.Sent
Sent --> Completed

Completed: ИдСостояния: State.Completed
Completed --> [*]
Canceled --> [*]
@enduml