@startuml
actor Барыга as Sidor
actor Сталкер as Stalker
actor Клиент as Client
actor Информатор as Informator
actor "Торговец оружием" as GunSeller
actor Курьер as Courier
actor Пользователь as User

User<|-- Sidor
User<|-- Stalker
User<|-- Client
User<|-- Informator
User<|-- GunSeller
User<|-- Courier


package Артефактик {

    usecase "Регистрация" as Register
    
    usecase "Выбор роли" as SelectRole

    usecase "Ввод почты и пароля" as InputData

    usecase "Просмотр списка ролей" as OpenRoles

    Register .-down-> InputData: Includes
    Register.> SelectRole: Includes
    SelectRole.> OpenRoles: Includes

}

User --> Register



@enduml