@startuml
|Клиент|
start
:Зайтии в приложение;
:Создать заказ;

|Барыга|
:Принять заказ;
:Предложить заказ сталкеру;

|Сталкер|
:Принять заказ;
:Выполнить заказ;

|Барыга|
:Отрпавить заказ клиенту;

|Клиент|
:Забрать заказ;

stop
@enduml