@startuml
|Клиент|
start
:Зайтии в приложение;
:Выбрать артефакт;
:Создать заказ;

|Барыга|
:Получить уведомление о новом заказе;
if (заказ устраивает) then (да)
    :Принять заказ;
else (нет)
    :Отклонить заказ;
endif

|Клиент|
:Получить уведомление о изменении статуса заказа;

stop
@enduml









#@startuml
#|Клиент|
#start
#:Зайтии в приложение;
#:Создать заказ;
#
#|Барыга|
#:Принять заказ;
#:Предложить заказ сталкеру;
#
#|Сталкер|
#:Принять заказ;
#:Выполнить заказ;
#
#|Барыга|
#:Отрпавить заказ клиенту;
#
#|Клиент|
#:Забрать заказ;
#
#stop
#@enduml