
@startuml

Барыга -> Барыга: Открыть список принятых заказов
Барыга -> Барыга: Выбрать заказ

Барыга -> Барыга: Открыть список доступных сталкеров
Барыга -> Сталкер: Выбрать сталкера

Сталкер -> Сталкер: Посмотреть информацию о заказе

alt заказ устраивает
    Сталкер -> Барыга: Принять заказ
else заказ не устраивает
    Сталкер -> Барыга: Отклонить заказ
end


@enduml


//@startuml
//
//Клиент->Клиент: Ввод логина и пароля
//
//Клиент-> Система: Авторизация в системе
//Система-> Клиент: Доступ к функционалу
//
//Клиент-> Система: Запрос списка артефактов
//Система-> Клиент: Список артефактов
//
//Клиент -> Клиент: Заполнение данных о заказе
//
//Клиент -> Система: Создание нового заказа
//Система -> Клиент: Заказ создан
//
//@enduml


//@startuml
// Клиент-> Система: Авторизация в системе
// Система-> Клиент: Доступ к функционалу

// Клиент -> Система: создать заказ
// Система -> Барыга: уведомление о заказе

// Барыга -> Клиент: Принять заказ
// Барыга -> Сталкер: Предложить заказ
// Сталкер -> Барыга: Принять заказ

// Сталкер->Барыга: Выполнить заказ
// Барыга -> Клиент: Выполнить заказ

// Клиент-> Система: оплатить заказ
// @enduml

