
@startuml
Клиент-> Система: Авторизация в системе
Система-> Клиент: Доступ к функционалу

Клиент-> Система: Запрос списка артефактов
Система-> Клиент: Список артефактов

Клиент -> Система: Создание нового заказа
Система -> Клиент: Заказ создан

@enduml


//@startuml
// Клиент-> Система: Авторизация в системе
// Система-> Клиент: Доступ к функционалу

// Клиент -> Система: создать заказ
// Система -> Барыга: уведомление о заказе

// Барыга -> Клиент: Принять заказ
// Барыга -> Сталкер: Предложить заказ
// Сталкер -> Барыга: Принять заказ

// Сталкер->Барыга: Выполнить заказ
// Барыга -> Клиент: Выполнить заказ

// Клиент-> Система: оплатить заказ
// @enduml

