@startuml


state "Новый заказ" as NewOrder
state "Принят" as AcceptedByHuckster
state "В процессе" as InProgress
state "Готов" as TransferredToHuckster
state "Отправлен клиенту" as Sent
state "Завершен" as Completed
[*] -right-> NewOrder
NewOrder -right-> AcceptedByHuckster
AcceptedByHuckster -right-> InProgress
InProgress -down-> TransferredToHuckster
TransferredToHuckster -left-> Sent
Sent -left-> Completed
Completed --> [*]
@enduml