@startuml logical-view

package auth as "Авторизация" {
    package "Регистрация"

    package "Аутентификация"
}

package main as "Меню" {
    package "Заказ" {
        package "Создание заказа"

        package "Управление заказом"
    }

    package notice as "Уведомления" {

    }
}

auth ..> main

@enduml